persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Permite conexões de fora do container e sem autenticação (para teste)
listener 1883
allow_anonymous true